name: m3u8 Extractor

on:
  schedule:
    - cron: '0 * * * *' # Her saat başı
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run extractor
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }}
          WORKER_UPDATE_URL: ${{ secrets.WORKER_UPDATE_URL }}
          WORKER_SECRET: ${{ secrets.WORKER_SECRET }}
          ATTEMPTS: 1
        run: node extract-and-send.js
