name: extract-and-update

on:
  schedule:
    - cron: '*/5 * * * *' # her 5 dakikada bir
  workflow_dispatch: {} # manuel tetikleme

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: Run Playwright extraction
        uses: microsoft/playwright-github-action@v1
        with:
          run: node extract-and-send.js
        env:
          TARGET_PAGE: ${{ secrets.TARGET_PAGE }}
          WORKER_UPDATE_URL: ${{ secrets.WORKER_UPDATE_URL }}
          WORKER_SECRET: ${{ secrets.WORKER_SECRET }}
