name: Extract and Send

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run extractor
        run: node extract-and-send.js
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }}
          WORKER_UPDATE_URL: ${{ secrets.WORKER_UPDATE_URL }}
          WORKER_SECRET: ${{ secrets.WORKER_SECRET }}
